// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: delivery/delete_entries.proto

package deliverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Auth          *AuthData      `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Id            string         `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Filter        *EntryFilter   `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	EventMetadata *EventMetadata `protobuf:"bytes,5,opt,name=eventMetadata,proto3" json:"eventMetadata,omitempty"`
}

func (x *DeleteEntriesRequest) Reset() {
	*x = DeleteEntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_delete_entries_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntriesRequest) ProtoMessage() {}

func (x *DeleteEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_delete_entries_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntriesRequest.ProtoReflect.Descriptor instead.
func (*DeleteEntriesRequest) Descriptor() ([]byte, []int) {
	return file_delivery_delete_entries_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteEntriesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeleteEntriesRequest) GetAuth() *AuthData {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *DeleteEntriesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteEntriesRequest) GetFilter() *EntryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DeleteEntriesRequest) GetEventMetadata() *EventMetadata {
	if x != nil {
		return x.EventMetadata
	}
	return nil
}

type DeleteEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfDeletedEntries int64 `protobuf:"varint,1,opt,name=numberOfDeletedEntries,proto3" json:"numberOfDeletedEntries,omitempty"`
}

func (x *DeleteEntriesResponse) Reset() {
	*x = DeleteEntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_delete_entries_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntriesResponse) ProtoMessage() {}

func (x *DeleteEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_delete_entries_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntriesResponse.ProtoReflect.Descriptor instead.
func (*DeleteEntriesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_delete_entries_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteEntriesResponse) GetNumberOfDeletedEntries() int64 {
	if x != nil {
		return x.NumberOfDeletedEntries
	}
	return 0
}

var File_delivery_delete_entries_proto protoreflect.FileDescriptor

var file_delivery_delete_entries_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x1a, 0x15, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xd0, 0x01, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a,
	0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x4f, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x16,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x45,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delivery_delete_entries_proto_rawDescOnce sync.Once
	file_delivery_delete_entries_proto_rawDescData = file_delivery_delete_entries_proto_rawDesc
)

func file_delivery_delete_entries_proto_rawDescGZIP() []byte {
	file_delivery_delete_entries_proto_rawDescOnce.Do(func() {
		file_delivery_delete_entries_proto_rawDescData = protoimpl.X.CompressGZIP(file_delivery_delete_entries_proto_rawDescData)
	})
	return file_delivery_delete_entries_proto_rawDescData
}

var file_delivery_delete_entries_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_delivery_delete_entries_proto_goTypes = []interface{}{
	(*DeleteEntriesRequest)(nil),  // 0: delivery.DeleteEntriesRequest
	(*DeleteEntriesResponse)(nil), // 1: delivery.DeleteEntriesResponse
	(*AuthData)(nil),              // 2: delivery.AuthData
	(*EntryFilter)(nil),           // 3: delivery.EntryFilter
	(*EventMetadata)(nil),         // 4: delivery.EventMetadata
}
var file_delivery_delete_entries_proto_depIdxs = []int32{
	2, // 0: delivery.DeleteEntriesRequest.auth:type_name -> delivery.AuthData
	3, // 1: delivery.DeleteEntriesRequest.filter:type_name -> delivery.EntryFilter
	4, // 2: delivery.DeleteEntriesRequest.eventMetadata:type_name -> delivery.EventMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_delivery_delete_entries_proto_init() }
func file_delivery_delete_entries_proto_init() {
	if File_delivery_delete_entries_proto != nil {
		return
	}
	file_delivery_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_delivery_delete_entries_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_delete_entries_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delivery_delete_entries_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_delete_entries_proto_goTypes,
		DependencyIndexes: file_delivery_delete_entries_proto_depIdxs,
		MessageInfos:      file_delivery_delete_entries_proto_msgTypes,
	}.Build()
	File_delivery_delete_entries_proto = out.File
	file_delivery_delete_entries_proto_rawDesc = nil
	file_delivery_delete_entries_proto_goTypes = nil
	file_delivery_delete_entries_proto_depIdxs = nil
}
