// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: delivery/shared.proto

package deliverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrudAuthData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string            `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scopes   []string          `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Data     map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CrudAuthData) Reset() {
	*x = CrudAuthData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_shared_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrudAuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrudAuthData) ProtoMessage() {}

func (x *CrudAuthData) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_shared_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrudAuthData.ProtoReflect.Descriptor instead.
func (*CrudAuthData) Descriptor() ([]byte, []int) {
	return file_delivery_shared_proto_rawDescGZIP(), []int{0}
}

func (x *CrudAuthData) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CrudAuthData) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *CrudAuthData) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type EntryFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields map[string]*EntryFieldFilter `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	And    []*EntryFilter               `protobuf:"bytes,2,rep,name=and,proto3" json:"and,omitempty"`
	Or     []*EntryFilter               `protobuf:"bytes,3,rep,name=or,proto3" json:"or,omitempty"`
}

func (x *EntryFilter) Reset() {
	*x = EntryFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_shared_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryFilter) ProtoMessage() {}

func (x *EntryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_shared_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryFilter.ProtoReflect.Descriptor instead.
func (*EntryFilter) Descriptor() ([]byte, []int) {
	return file_delivery_shared_proto_rawDescGZIP(), []int{1}
}

func (x *EntryFilter) GetFields() map[string]*EntryFieldFilter {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *EntryFilter) GetAnd() []*EntryFilter {
	if x != nil {
		return x.And
	}
	return nil
}

func (x *EntryFilter) GetOr() []*EntryFilter {
	if x != nil {
		return x.Or
	}
	return nil
}

type EntryFieldFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Operation string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Value     string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EntryFieldFilter) Reset() {
	*x = EntryFieldFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_shared_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryFieldFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryFieldFilter) ProtoMessage() {}

func (x *EntryFieldFilter) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_shared_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryFieldFilter.ProtoReflect.Descriptor instead.
func (*EntryFieldFilter) Descriptor() ([]byte, []int) {
	return file_delivery_shared_proto_rawDescGZIP(), []int{2}
}

func (x *EntryFieldFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntryFieldFilter) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *EntryFieldFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CrudEventMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CausationId   string `protobuf:"bytes,1,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
}

func (x *CrudEventMetadata) Reset() {
	*x = CrudEventMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_shared_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrudEventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrudEventMetadata) ProtoMessage() {}

func (x *CrudEventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_shared_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrudEventMetadata.ProtoReflect.Descriptor instead.
func (*CrudEventMetadata) Descriptor() ([]byte, []int) {
	return file_delivery_shared_proto_rawDescGZIP(), []int{3}
}

func (x *CrudEventMetadata) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *CrudEventMetadata) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_delivery_shared_proto protoreflect.FileDescriptor

var file_delivery_shared_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x22, 0xb2, 0x01, 0x0a, 0x0c, 0x43, 0x72, 0x75, 0x64, 0x41, 0x75, 0x74, 0x68, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x2e, 0x43, 0x72, 0x75, 0x64, 0x41, 0x75, 0x74, 0x68, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a,
	0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xef, 0x01, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x12, 0x27, 0x0a, 0x03, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x03, 0x61, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x02, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x02, 0x6f,
	0x72, 0x1a, 0x55, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5a, 0x0a, 0x10, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x5d, 0x0a, 0x11, 0x43, 0x72, 0x75, 0x64, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x75,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x61, 0x75, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delivery_shared_proto_rawDescOnce sync.Once
	file_delivery_shared_proto_rawDescData = file_delivery_shared_proto_rawDesc
)

func file_delivery_shared_proto_rawDescGZIP() []byte {
	file_delivery_shared_proto_rawDescOnce.Do(func() {
		file_delivery_shared_proto_rawDescData = protoimpl.X.CompressGZIP(file_delivery_shared_proto_rawDescData)
	})
	return file_delivery_shared_proto_rawDescData
}

var file_delivery_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_delivery_shared_proto_goTypes = []interface{}{
	(*CrudAuthData)(nil),      // 0: delivery.CrudAuthData
	(*EntryFilter)(nil),       // 1: delivery.EntryFilter
	(*EntryFieldFilter)(nil),  // 2: delivery.EntryFieldFilter
	(*CrudEventMetadata)(nil), // 3: delivery.CrudEventMetadata
	nil,                       // 4: delivery.CrudAuthData.DataEntry
	nil,                       // 5: delivery.EntryFilter.FieldsEntry
}
var file_delivery_shared_proto_depIdxs = []int32{
	4, // 0: delivery.CrudAuthData.data:type_name -> delivery.CrudAuthData.DataEntry
	5, // 1: delivery.EntryFilter.fields:type_name -> delivery.EntryFilter.FieldsEntry
	1, // 2: delivery.EntryFilter.and:type_name -> delivery.EntryFilter
	1, // 3: delivery.EntryFilter.or:type_name -> delivery.EntryFilter
	2, // 4: delivery.EntryFilter.FieldsEntry.value:type_name -> delivery.EntryFieldFilter
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_delivery_shared_proto_init() }
func file_delivery_shared_proto_init() {
	if File_delivery_shared_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_delivery_shared_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrudAuthData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_shared_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_shared_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryFieldFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_shared_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrudEventMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delivery_shared_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_shared_proto_goTypes,
		DependencyIndexes: file_delivery_shared_proto_depIdxs,
		MessageInfos:      file_delivery_shared_proto_msgTypes,
	}.Build()
	File_delivery_shared_proto = out.File
	file_delivery_shared_proto_rawDesc = nil
	file_delivery_shared_proto_goTypes = nil
	file_delivery_shared_proto_depIdxs = nil
}
